import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import fileRoutes from './file.routes.js';
import programKerjaRoutes from './program-kerja.routes.js';
import rkapRoutes from './rkap.routes.js';
import sdmRoutes from './sdm.routes.js';
import licenseRoutes from './license.routes.js';
import ketersediaanScmcRoutes from './ketersediaan-scmc.routes.js';
import ketersediaanSistemRoutes from './ketersediaan-sistem.routes.js';
import utilisasiCpuRoutes from './utilisasi-cpu.routes.js';
import utilisasiCpuDbRoutes from './utilisasi-cpu-db.routes.js';
import utilisasiMemoryRoutes from './utilisasi-memory.routes.js';
import utilisasiMemoryDbRoutes from './utilisasi-memory-db.routes.js';
import utilisasiStorageRoutes from './utilisasi-storage.routes.js';
import utilisasiStorageDbRoutes from './utilisasi-storage-db.routes.js';
import utilisasiCpuAppRoutes from './utilisasi-cpu-app.routes.js';
import utilisasiBandwidthRoutes from './utilisasi-bandwidth.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/files', fileRoutes);
router.use('/program-kerja', programKerjaRoutes);
router.use('/rkap', rkapRoutes);
router.use('/sdm', sdmRoutes);
router.use('/licenses', licenseRoutes);
router.use('/ketersediaan/scmc', ketersediaanScmcRoutes);
router.use('/ketersediaan/sistem', ketersediaanSistemRoutes);
router.use('/utilisasi/cpu', utilisasiCpuRoutes);
router.use('/utilisasi/cpu-database', utilisasiCpuDbRoutes);
router.use('/utilisasi/memory', utilisasiMemoryRoutes);
router.use('/utilisasi/memory-database', utilisasiMemoryDbRoutes);
router.use('/utilisasi/storage', utilisasiStorageRoutes);
router.use('/utilisasi/storage-database', utilisasiStorageDbRoutes);
router.use('/utilisasi/cpu-app', utilisasiCpuAppRoutes);
router.use('/utilisasi/bandwidth', utilisasiBandwidthRoutes);

export default router;
